version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(ruby)"

  - package-ecosystem: "devcontainers"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(devcontainer)"

  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "prod"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(ruby)"

  - package-ecosystem: "devcontainers"
    directory: "/"
    target-branch: "prod"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(devcontainer)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    # assignees and reviewers omitted

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    # assignees and reviewers omitted

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    target-branch: "prod"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    # assignees and reviewers omitted

  - package-ecosystem: "terraform"
    directory: "/infra"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    # assignees and reviewers omitted

  - package-ecosystem: "terraform"
    directory: "/infra"
    target-branch: "prod"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    # assignees and reviewers omitted
