version: 0.2
env:
    shell: bash
    secrets-manager:
        AWS_ACCESS_KEY_ID: "cloudformationkeys:AWS_ACCESS_KEY_ID"
        AWS_SECRET_ACCESS_KEY: "cloudformationkeys:AWS_SECRET_ACCESS_KEY"

phases:
    install:
        runtime-versions:
            ruby: 3.3
            nodejs: 20
    pre_build:
        commands:
            - "bundle install"
            - "npm i -g serverless"
            - "serverless plugin install -n serverless-s3-sync"
    build:
        commands:
            - "bundle exec jekyll build"
    post_build:
        commands:
            - "serverless deploy -s prod"
artifacts:
    files:
        - "**/*"
    base-directory: "_site"
